name: build-html

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install eleventy
        run: npm install -g @11ty/eleventy

      - name: Build the website
        run: make

      - name: Add extra files for GitHub pages
        run: |
          touch _site/.nojekyll
          echo "www.acarolcolombo.com" > _site/CNAME

      - name: Push to acarolcolombo.github.io
        if: success() && github.event_name == 'push'
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: acarolcolombo/acarolcolombo.github.io
          publish_branch: master
          publish_dir: ./_site
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
